// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.p
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGT7HnaqQ-2eZ7z3X0NrsJNhOR-Yql2OM',
    appId: '1:262176727818:web:64173072bc9a9aae0250f3',
    messagingSenderId: '262176727818',
    projectId: 'bookstore-dffe4',
    authDomain: 'bookstore-dffe4.firebaseapp.com',
    storageBucket: 'bookstore-dffe4.appspot.com',
    measurementId: 'G-7EM57WFCEM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqbtw9vNC4ASTNKtXknYCzulKTlaiWU7k',
    appId: '1:262176727818:android:61cb860f59cb44500250f3',
    messagingSenderId: '262176727818',
    projectId: 'bookstore-dffe4',
    storageBucket: 'bookstore-dffe4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChKfIihTDyW25jqN2b7YHl9OVuEFXkp2M',
    appId: '1:262176727818:ios:67e891adcf552d3e0250f3',
    messagingSenderId: '262176727818',
    projectId: 'bookstore-dffe4',
    storageBucket: 'bookstore-dffe4.appspot.com',
    iosBundleId: 'com.example.baiTestIntern',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyChKfIihTDyW25jqN2b7YHl9OVuEFXkp2M',
    appId: '1:262176727818:ios:8ba72feafcc729240250f3',
    messagingSenderId: '262176727818',
    projectId: 'bookstore-dffe4',
    storageBucket: 'bookstore-dffe4.appspot.com',
    iosBundleId: 'com.example.baiTestIntern.RunnerTests',
  );
}
